version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    env_file:
      - skymarket/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: frontend_react/.
    depends_on:
      - db

  api:
    build: skymarket/.
    env_file:
      - skymarket/.env
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ./skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - db
      - frontend
      - api
